# Generated by Django 4.1.3 on 2022-11-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=256)),
                ('ip_addr', models.GenericIPAddressField()),
                ('browser', models.CharField(max_length=256)),
                ('request_params', models.TextField()),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
    ]
