# Generated by Django 4.1.3 on 2022-11-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_basestatistic_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basestatistic',
            name='user',
        ),
    ]
